### ISSUE TITLE
CITY - Main Roadmap 

### ISSUE THREAD

**Issue by 1B0Y** [1B0Y/RETRONetwork-Public#65]
Below is a list of features, changes and fixes to be placed into the server before 1.0 can be announced released.

- [x] Core: strip restricted job-based system
- [x] Core: update logging for all interactions such as item usage, money, weapons, etc.
- [x] Core: adjust player payments, stress, metabolism and etc
- [x] Characters: Fix character creation NPC showing to others (SetPlayerRoutingBucket)
- [x] Characters: Deleting NPCs sometimes results in the ped not deleting.
- [x] Characters: New players aren't getting starting items since logging update.
- [ ] Characters: Update character creation UI - sliders for facial features rather than left/right buttons for better customisation, 2nd variable for some aspects such as hair to add 2 tone, …
- [x] Core: whitelistedJobs is not saving correctly into the database.
- [x] Characters: Fix issue where cancelling character creation will result in an “invisible” character
- [x] Characters: Update character selection area to the nightclub
- [x] Characters: Add spotlight to show selected camera due to nightclub being dark.
- [x] Characters: Add random NPCs dancing in background to set the scene off more.
- [x] Characters: Update character creation area to the nightclub VIP section
- [x] Characters: Move first spawn to somewhere else in the city.
- [ ] Characters: Make camera be controlled by mouse input (click and drag up / down to move the camera height, click and drag left / right to rotate the NPC, scroll wheel to zoom in) - PART OF CLOTHING SYSTEM
- [x] Characters: Change starting items
- [x] Misc: Disable idle camera
- [x] Radio: Fix the annoying ass "You left the channel" even though we don't have a radio...
- [x] Stress: Increase trigger value for unbuckled seats due to stress gaining too fast.
- [x] Loading Screen: Update random quotes to not repeat again and again.
- [x] Prison: Install MLO to take advantage of visiting zone, better cells and etc.
- [ ] Stop doors from being unlocked when in a locked state.
- [ ] Police: Introduce a new CAD system
- [x] Phone: Remove old MDT system that is barely functional
- [ ] Police: Install new MLO for the station
- [ ] Police: Relocate all job aspects
- [ ] Core: introduce whitelisted system for jobs (PD, EMS, …)
- [ ] Police: Develop new evidence locker that can be linked to the CAD system
- [ ] Police: Introduce new police vehicles that can be purchased based on job grading (linked in with whitelisting system, hooked into the vehicle system)
- [ ] Police: Create new armoury for cops, and have items available based on job grade
- [ ] Radial/Police: Fix job aspects that are broken (officer down, tow, etc)
- [ ] Vehicles: Update Garage locations to be more suitable around the city
- [ ] Zones: Add Fort Zancudo as restricted area, entering will send a jet to shoot them
- [ ] Mod shops: Re-enable Bennys to take payments now the money issue is fixed.
- [ ] Mod shops: Add blips for players
- [ ] Mod shops: Disable tuning options in Bennys. Only mechanics can perform this.
- [ ] Mod shops: Disable mod area completely if a mechanic is online and on duty
- [ ] Mechanic: strip job out to be rewritten
- [ ] Mechanic: Add 3 shops in city for mechanics to work at
- [ ] Mechanic: Add repair parts into the shops that can be purchased for $10 a piece
- [ ] Mechanic: Add option at repair shops for players to repair their own vehicles for a set fee (Formula: math.floor(1,500 - vehicleHealth))
- [ ] Tow Truck: Add job - players will need to buy their own tow truck.
- [ ] Tow Truck: Add option to tow vehicles.
- [ ] Lock-picking: Change from fallout style lock picking to progression bar. Skill will be attached to this.
- [ ] Mining: Add pick axe item to hardware stores
- [ ] Mining: Add PolyZone around the pits near sandy, and the mines outside the winery
- [ ] Mining: Create functionality to the pick axe item to start mining when in the zones
- [ ] Smelter: Create the smelter in the city where players can smelt down their mined ore
- [ ] Mining: Create a sell point for players to sell the refined ore
- [ ] Jewellers: Create a new store where players can sell their mined jewels or buy jewels as well
- [ ] Mining: Add a process where rough jewels can be processed into grade A-C quality items
- [ ] Hospital: Update MLO to the known pillbox MLO everyone is used to
- [ ] Hospital: Respawn players to the nearest hospitals
- [ ] Hospital: Add MLO for Sandy and Paleto
- [ ] Hospital: Add exception for players to respawn without loosing their items if no paramedics are online
- [ ] Paramedic: Add appropriate vehicles and clothing
- [ ] Paramedic: Create CAD system for medical documentation
- [ ] Paramedic: Add appropriate items into lockers for medics to do their role (med kits, pain killers, bandages, stretchers, etc)
- [ ] Garbage Collection: Create job near Bennys
- [ ] Garbage Collection: Create table of locations of the bins. When job is activated (holding G) it’ll start the job for the player.
- [ ] Garbage Collection: Add a zone so the player does not get the same bins nearby, forcing them to move on
- [ ] Garbage Collection: Add total weight limit to garbage truck, once filled the player can no longer empty bins
- [ ] Garbage Collection: Force players to pull trash bags out of the truck at the depo to empty garbage truck
- [ ] Vehicles: Add wear and tear system in, such as broken drive shaft resulting in top speed being randomised or no drive at all, tyre wear which reduces grip, blowing up an engine, radiator leak resulting in engine potentially blowing up / cutting out, fuel tank damage resulting in fuel spilling out, etc
- [ ] Mining: Add Silicon to mining to craft plastic
- [ ] Chop Shop: add option for criminals to steal certain cars listed on storm, 10 cars per storm, and will give a specific amount of money + car parts
- [ ] Wrench Tool: Add option for criminals to steal parts off vehicles. (Cannot steal off players vehicles)
- [ ] Taxi: Add option to hold down G to start an NPC pickup job
- [ ] Weapons: Implement new realistic models into the city 
- [ ] Weapons: Introduce new recoil system
- [ ] Weapons: Add crosshair if the attachment is added.
- [ ] Weapons: Add a criminal option to scratch off the serial number off a weapon (file required)
- [ ] Vehicles: Add option for players to create false plates (which can be pulled off / put on) - option for prison job - will drop with a 5%
- [ ] Tattoo Shop: make it a thing
- [ ] Tattoo Shop: Tattoo Catalog with actual tattoo names and prices, along with images of where the tattoos are. (Being discussed with Roland)

(more to be added to this list as we go along)
