### ISSUE TITLE
MC - Roadmap

### ISSUE THREAD

**Issue by DLmass** [1B0Y/RETRONetwork-Public#66]
**Ingame**
- [ ] Figure out ways to earn money such as jobs, sell items to the server and etc
- [ ] Individual unlockable achievements which would unlock different aspects of the server such a nether, end, upgradable tools and blocks allowed to mine. Find ways to keep players coming back.
- [ ] Server phases (I, II, III)
- [ ] Make it more competitive such as teams/clans which would fight for the top 

**QuickShop**
- [x] Setup and make it work properly

**AuctionHouse**
- [x] Setup and make it work properly

**LiteBans**
- [ ] Setup and make it work properly for staff members ingame

**LiteBansBridge**
- [ ] Setup and make it work properly for staff to see punishments on discord

**DiscordSRV**
- [x] Setup the bot to output to game and mc-server
- [x] Sync Discord roles with Luckperms

**Luckperms**

_Ranks_
- [x] Add Member
- [x] Add Donator
- [x] Add Moderator
- [x] Add Admin
- [x] Add OP

_Permissions_
- [ ] Add proper permissions for each rank
- [ ] Add color prefixes for each rank

**EssentialsX**
- [ ] Setup and limit the usage
- [ ] Change the chat formatting
- [ ] Change the money they get when they join the server for the first time

**WorldGuard**
- [ ] Prevent default rank from interacting with the world
- [ ] Add a message for default rank that they cannot interact and has to join the discord to agree with the rules to be able to build
- [ ] Add so member, donator, moderator, admin and OP can interact with the world normally
- [ ] All above should apply to world_nether and world_end
- [ ] Prevent Creeper damage (for now)
- [ ] Prevent Enderman grief (for now)

**NuVotifier & SimpleVotes**
- [ ] Setup voting websites
- [ ] Make payout realistic so the economy raises slowly and steady

**Realistic Seasons**
- [ ] Buy the plugin and set it up to work properly

**Donations**
- [ ] Look into which plugin suits our needs
- [ ] Setup rewards that follow the EULA and will not make the server pay 2 win and players not too OP
- [ ] Individual donator Islands
- [ ] Donator vaults
- [ ] Cosmetics
- [ ] Crates
